// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAnl0zktR8H7auddWKH9SyfNLg0gPGJF4',
    appId: '1:712752757972:android:adc23f222091e85de14f41',
    messagingSenderId: '712752757972',
    projectId: 'konektchat',
    storageBucket: 'konektchat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX1tIqEOmsG-VhDQ5a2CvbmDBPqYZNA6o',
    appId: '1:712752757972:ios:0536e702a27190fce14f41',
    messagingSenderId: '712752757972',
    projectId: 'konektchat',
    storageBucket: 'konektchat.firebasestorage.app',
    iosBundleId: 'com.example.konektChat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjaDZ4G8wSKnTtzceBbcX86KNH4YkbOrc',
    appId: '1:712752757972:web:b17fa3db41b6c62be14f41',
    messagingSenderId: '712752757972',
    projectId: 'konektchat',
    authDomain: 'konektchat.firebaseapp.com',
    storageBucket: 'konektchat.firebasestorage.app',
  );

}